### ISSUE TITLE
Integrate into existing influxdb / grafana solution ? 

### ISSUE THREAD

**Issue by anastazya** [victronenergy/venus-docker-grafana#10]
I want to integrate this into an existing docker-compose stack that has influxdb / grafana for other network related monitoring.
The only problem is that my influxdb uses authentication, and i can't find anywhere to set user / password / db to use it with my existing setup.

**Comment by robtor-de** [comment]
I think the only option to do that is to change the sourcecode of the server

Maybe you can change it here:

https://www.github.com/victronenergy/venus-docker-grafana-images/tree/master/server%2Flib%2Finfluxdb.js

But thats only a suggestion

**Comment by jeff-denning** [comment]
You can do this once you've set it up, I have existing InfluxDB and Grafana service running already, here's my docker-compose.yml - you change the rest in the web interface.

What the below does is setup Victron's UPNP discovery and web interface containers. Once done browse to the IP:port and go to InfluxDB, there you can enter your existing InfluxDB instance and obviously add that as a Grafana data source.

```version: '3.4'
services:
  server:
    image: "victronenergy/venus-docker-server:latest"
    ports:
     - "8088:8088"
    volumes:
     - /home/jeff/docker/victron:/config
  upnp:
    image: "victronenergy/venus-docker-upnp:latest"
    network_mode: host```

**Comment by robtor-de** [comment]
You could run the server with nodejs directly, but I think its much more complicated than using docker

**Comment by theimo1221** [comment]
I made a separate node.js package which connects to a local victron gx via mqtt and (if configured) stores the data into a separate influx instance.
The measurements in influx have the same id as I oriented my code on the servercode of this, so you could try this one:
https://github.com/theimo1221/victron-mqtt-consumer

**Comment by mman** [comment]
The ability to specify username/password for Influx has been addressed in https://github.com/victronenergy/venus-docker-grafana-images/pull/22 and will be released with the official release of https://github.com/victronenergy/venus-influx-loader in the near future.

**Comment by albundy0815** [comment]
> The ability to specify username/password for Influx has been addressed in [victronenergy/venus-docker-grafana-images#22](https://github.com/victronenergy/venus-docker-grafana-images/pull/22) and will be released with the official release of https://github.com/victronenergy/venus-influx-loader in the near future.

@mman is there a more "precise" timeline, when it's released or could be released?

**Comment by mman** [comment]
@albundy0815 I aim to get official 1.0 out of the door before end of this year. The code is stable and working nicely and requires only some polishing... here is the list of open issues to be fixed: https://github.com/victronenergy/venus-influx-loader/milestone/1

**Comment by albundy0815** [comment]
@mman  great news, so I'll wait till end of this year, because right now I tried a lot to get the solution of @theimo1221 via docker working, but I didn't. It seems that it's not easy as it seems ;(

**Comment by mman** [comment]
Please followup in the new repo https://github.com/victronenergy/venus-influx-loader if necessary. Closing here. @dirkjanfaber please close this issue.
