### ISSUE TITLE
How can I set this up entirely without docker ?

### ISSUE THREAD

**Issue by gidhap** [victronenergy/venus-docker-grafana#15]
I did the WIN10/Docker install and all is up and running.
However...
As I have InfluxDB and Grafana on Linux VMs already I'd prefer to link VRM to my existing influxDB.
How can I get the VRM data in my existing InfluxDB? 
Any help for a linux newbie aprecciated

**Comment by jeff-denning** [comment]
https://github.com/victronenergy/venus-docker-grafana/issues/10#issuecomment-693469632

**Comment by pkkrusty** [comment]
Anyone have any suggestions for this? I already have a Raspi running InfluxDB and Grafana and I want to integrate data from our Victron devices. I don't want to run a separate instance of either in docker.

**Comment by jeff-denning** [comment]
The issue I linked in my last comment has some tips. I personally haven't removed Docker completely, but I only run the container from Victron which just has a config to send data to InfluxDB.

Removing Docker entirely from the setup here is probably going to be a lot more complicated.

**Comment by pkkrusty** [comment]
I deleted the grafana and influx services from the yaml file like your linked comment and docker-compose'd the yaml, but seems like there's a conflict with my existing influxdb service, it has already bound port 8088. I had to rebuild the docker images with a random port pointing mapping to 8088 in the victron docker image and now things are working correctly. My yaml below:
```version: '3.4'
services:
  server:
    image: "victronenergy/venus-docker-server:latest"
    ports:
     - "8090:8088"
    volumes:
     - "config-storage:/config"
  upnp:
    image: "victronenergy/venus-docker-upnp:latest"
    network_mode: host    
volumes:
 config-storage:
```
I am noticing that the CerboGX dumps a TON of metrics in InfluxDB, and in my grafana, the dropdown is limited to 100 choices. You know any way to get more?

**Comment by jeff-denning** [comment]
> I am noticing that the CerboGX dumps a TON of metrics in InfluxDB, and in my grafana, the dropdown is limited to 100 choices. You know any way to get more?

Workaround discussed in https://github.com/victronenergy/venus-docker-grafana/issues/8

**Comment by theimo1221** [comment]
I made a separate node.js package which connects to a local victron gx via mqtt and (if configured) stores the data into influx.
The measurements in influx have the same id as I oriented my code on the servercode of this, so you could try this one:
https://github.com/theimo1221/victron-mqtt-consumer

**Comment by mman** [comment]
I am currently experimenting with https://www.influxdata.com/time-series-platform/telegraf/ which can be configured rather quickly to consume MQTT, transform it in various ways, and store to various backends such as Influx. May be easier for some folks who prefer no code solutions...

**Comment by mman** [comment]
Please followup in the new repo https://github.com/victronenergy/venus-influx-loader if necessary. Closing here. @dirkjanfaber please close this issue.
