### ISSUE TITLE
Redirected to login screen after ~10 minutes

### ISSUE THREAD

**Issue by Tasemu** [victronenergy/venus-docker-grafana#16]
Is there any way to set grafana to keep the user logged in for a decent length of time. i have this set up on a tablet and am unable to use this currently as I need to continually log in. Thanks for any and all advice!

**Comment by jeff-denning** [comment]
There are some Grafana options available for this > https://grafana.com/docs/grafana/latest/auth/grafana/
You'll need to set these up in your docker-compose.yml file, not sure it's best to make these tweaks with the one in this repo - consider creating a stand alone Grafana container/instance for more flexibility.

**Comment by mman** [comment]
Just for the interested readers, Grafana can be configured externally via environment variables specified in `docker-compose.yaml` for example like this: https://github.com/mman/venus-docker-grafana-images/blob/970f8fdcc2018cb2eb290f65ceedc7afa095e80c/docker-compose-dev.yaml#L32 where environment variables match the grafana config variables in uppercase with `GF_` prepended. For example like this:

```
GF_LOG_MODE=console
GF_TOKEN_ROTATION_INTERVAL_MINUTES=10m
```

The login lifecycle related variables are described here: https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/

**Comment by mman** [comment]
Closing here as will not fix. @dirkjanfaber please close this issue.
