### ISSUE TITLE
Unused Grid Meter Phases crashes loader

### ISSUE THREAD

**Issue by howetech** [victronenergy/venus-docker-grafana#20]
I'm running a single phase ESS system through an emulated et340 meter, where the unsed phases are returning a value of 'NaN'

When the loader process sees the 'NaN' being returned it crashses and stops processing any more events.  This happens with both a locally connected device and also if pulling the data from the VRM portal.

Below are the error logs:

root-server-1    | [error] [loader] can't record N/xxxxxxxx/system/0/Ac/Grid/L3/Current: {"value": NaN}
root-server-1    | [error] [loader] Unexpected token N in JSON at position 10 SyntaxError: Unexpected token N in JSON at position 10
root-server-1    |     at JSON.parse (<anonymous>)
root-server-1    |     at Loader.onMessage (/usr/local/lib/node_modules/venus-docker-grafana-server/lib/loader.js:103:23)
root-server-1    |     at MqttClient.<anonymous> (/usr/local/lib/node_modules/venus-docker-grafana-server/lib/loader.js:344:10)
root-server-1    |     at MqttClient.emit (node:events:526:28)
root-server-1    |     at MqttClient._handlePublish (/usr/local/lib/node_modules/venus-docker-grafana-server/node_modules/mqtt/lib/client.js:987:12)
root-server-1    |     at MqttClient._handlePacket (/usr/local/lib/node_modules/venus-docker-grafana-server/node_modules/mqtt/lib/client.js:336:12)
root-server-1    |     at work (/usr/local/lib/node_modules/venus-docker-grafana-server/node_modules/mqtt/lib/client.js:292:12)
root-server-1    |     at Writable.writable._write (/usr/local/lib/node_modules/venus-docker-grafana-server/node_modules/mqtt/lib/client.js:302:5)
root-server-1    |     at doWrite (/usr/local/lib/node_modules/venus-docker-grafana-server/node_modules/readable-stream/lib/_stream_writable.js:428:64)
root-server-1    |     at writeOrBuffer (/usr/local/lib/node_modules/venus-docker-grafana-server/node_modules/readable-stream/lib/_stream_writable.js:417:5)
root-server-1    |     at Writable.write (/usr/local/lib/node_modules/venus-docker-grafana-server/node_modules/readable-stream/lib/_stream_writable.js:334:11)
root-server-1    |     at TLSSocket.ondata (node:internal/streams/readable:754:22)
root-server-1    |     at TLSSocket.emit (node:events:526:28)
root-server-1    |     at addChunk (node:internal/streams/readable:315:12)
root-server-1    |     at readableAddChunk (node:internal/streams/readable:289:9)
root-server-1    |     at TLSSocket.Readable.push (node:internal/streams/readable:228:10)

**Comment by mman** [comment]
This is an interesting one, I believe we need to fix this one in the code to skip processing invalid measurements like these, however I am trying to understand why a single phase system is even sending these values? D you think it could be related to your emulated meter not having anything to send and thus pushing NaN?

Note that loader code is being moved into https://github.com/victronenergy/venus-influx-loader/tree/main, but the issue will be present there as well, I do not think I changed anything around that in the new code...

**Comment by howetech** [comment]
So I've been playing with this a bit more and it doesn't stop processing data / events straight away, it seems to happen after successfully running for 16 - 24hrs, but the time to crash is not consistent.

I'm running an SMA Smart Manager 2.0 meter which is 3 phases, however I only have a single phase installation hence why the other 2 phases are reporting NILL / NULL data.   For reference I am running this script to emulate the ET340:

https://github.com/mitchese/shm-et340

When this happens the victron loader stops processing all data / events, not just the grid meter data.  Restarting the above shm-et340 program on VenusOS restores connectivity without touching the loader program.

Problem is that victron loader doesn't log anything specifc when it stops processing the data.  It is full of the above logs in my first post but these logs are constantly being written until the data just stops being processed.  Even the debug log flag doesn't show any additional info.   I'm wondering if some logbuffer is being filled with these "NaN" errors and causing it to stop after a period of time.

**Comment by mman** [comment]
@howetech I do not have the meter at hand to test, but I tried to understand the code of `shm-et340` and I think here is the main line https://github.com/mitchese/shm-et340/blob/6661fcd54013a38d144a1a41c2e2c79f53e0a956/main.go#L286 that should report to a debug log what value(s) for L1, L2, L3 were decoded when receiving an update from the meter before being pushed out to DBUS.

Could you post here what is the et340 reporting?

Martin

**Comment by howetech** [comment]
It is reporting NaN for the current output on the unused phases:

2023/10/16 08:34:47 Received datagram from meter
2023/10/16 08:34:47 Uid:  262816
2023/10/16 08:34:47 Serial:  3012879511
2023/10/16 08:34:47 Total W:  1.7
2023/10/16 08:34:47 Total Buy kWh:   2017.5726000000002
2023/10/16 08:34:47 Total Sell kWh:  7154.4002
2023/10/16 08:34:47 +-----+-------------+---------------+---------------+
2023/10/16 08:34:47 |value|   L1        |     L2        |   L3          |
2023/10/16 08:34:47 +-----+-------------+---------------+---------------+
2023/10/16 08:34:47 |  V  |   236.04    |     0.00      |     0.00      |
2023/10/16 08:34:47 |  A  |     0.01    |      NaN      |      NaN      |
2023/10/16 08:34:47 |  W  |     1.70    |     0.00      |     0.00      |
2023/10/16 08:34:47 | kWh |  2017.57    |     0.00      |     0.00      |
2023/10/16 08:34:47 | kWh |  7154.40    |     0.00      |     0.00      |
2023/10/16 08:34:47 +-----+-------------+---------------+---------------+

This is what the Venus OS is showing for the grid meter:

![image](https://github.com/victronenergy/venus-docker-grafana/assets/87409680/7f8bb372-8b90-4fe1-8340-b6c185a6f6a3)

**Comment by mman** [comment]
Thanks for the copy, I think this is the main problem. It reports Voltage and Wattage as 0 on unused phases, and Amperage as NaN, that is clearly a bug that should be addressed in the https://github.com/mitchese/shm-et340 repo. Amperage should never be a NaN.

I have been thinking about how to best fix this at the https://github.com/victronenergy/venus-influx-loader side, but it's not trivial because DBUS payload is not typed, and in fact contains arbitrary values. 

For example see here: https://github.com/mman/venus-mqtt-telegraf-timescaledb#mqtt-payload-structure

It can contain `string` for some fields, and `float` for other fields, and `object` for other fields without knowing it in advance. So I can theoretically detect a `NaN` or `"NaN"` and try to replace it with `0`, but I am thinking that https://github.com/mitchese/shm-et340 should not push out `NaN` in the first place as it does not have any correspondence to the real world. 

What do you think?

**Comment by howetech** [comment]
Makes sense and I agree that it should be fixed at the source.

I'll raise a issue against it on the et340 repo and see how I go.  Worst case it looks lke the et340 sets an initial value of 0 for the current so I might be able to comment out the updates to this record on the L2 & L3 phases so it remains at the initla value of 0.

Thanks for looking into it.

**Comment by mman** [comment]
That was my thinking as well, the code looks pretty simple and the fix should be easy there...

**Comment by mman** [comment]
Closing here as will not fix. @dirkjanfaber please close this issue.
