### ISSUE TITLE
Connect to different mqtt url based on portal id

### ISSUE THREAD

**Issue by sbender9** [victronenergy/venus-docker-grafana#6]
https://github.com/victronenergy/venus/issues/543

**Comment by sbender9** [comment]
@mpvader It looks like I'm going to have to do some re-architecting here since the code supports multiple devices and assumes that I just need one mqtt connection. Not a huge deal, but a bit more complicated than I thought it would be. (Same with changes to WilhelmSK)

**Comment by mpvader** [comment]
Understood. It is what it is, go for it
