### ISSUE TITLE
Amazing APP

### ISSUE THREAD

**Issue by denzelm5** [victronenergy/venus-docker-grafana#7]
Hi,

Thanks for this amazing app! im hosting this on Docker and works great. 

Can you post some data sources should on want to change the dashboard stats eg: I don't have a tank , lets say I want to display PV Stats? 

Regards
Denzel

**Comment by mpvader** [comment]
Hi @denzelm5,

Could you ask your question [here on the modification space on Community](https://community.victronenergy.com/spaces/31/index.html)? There will be more people there to help answering.

Please use docker-grafana in the title and explain a bit further what it is your looking for.

thanks, I'll close this issue now.
