### ISSUE TITLE
Grafana query search limits the shown measurements to 100

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus-docker-grafana#8]
Below screenshot show the dropdown thats limit to 100 entries.

It being limited is an issue since some items have more than 100. So even if the user knows the name of the service of which he is looking for data (ie battery, vebus, settings), then still he doesn't get to see all paths.

And having all paths available to browse through to see whats available and to know how the path is named that you are looking for is essential for this grafana solution to be usuable.

One solution is to add a dashboard that shows all measurements. Which Teun already did and of which I'll post the JSON below, also for the benefit of people now looking to solve their issue.

Suggested solutions:

1. Add below pasted dashboard to the pre-installed dashboards
2. Patch Grafana to limit to 250 lines instead of 100. Reading [this link](https://github.com/grafana/grafana/issues/2524) looks to show where the patch needs to be made

This was discussed extensively in our venus-docker-grafana slack in the past few days.

![image](https://user-images.githubusercontent.com/5200296/82207087-90b8b180-9909-11ea-909e-7a529d7b869e.png)

**Comment by mpvader** [comment]
the dashboard that shows all measurements, as made by Teun.

@anyone looking to use this now, look for the "Import" feature in Grafana (or google it).

```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 5,
  "links": [],
  "panels": [
    {
      "columns": [],
      "fontSize": "100%",
      "gridPos": {
        "h": 24,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "links": [],
      "pageSize": 100000,
      "scroll": true,
      "showHeader": true,
      "sort": {
        "col": 0,
        "desc": false
      },
      "styles": [
        {
          "alias": "Time",
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "pattern": "Time",
          "type": "date"
        },
        {
          "alias": "",
          "colorMode": null,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "decimals": 2,
          "pattern": "/.*/",
          "thresholds": [],
          "type": "number",
          "unit": "short"
        }
      ],
      "targets": [
        {
          "groupBy": [
            {
              "params": [
                "$__interval"
              ],
              "type": "time"
            },
            {
              "params": [
                "null"
              ],
              "type": "fill"
            }
          ],
          "orderByTime": "ASC",
          "policy": "default",
          "query": "SHOW MEASUREMENTS",
          "rawQuery": true,
          "refId": "A",
          "resultFormat": "table",
          "select": [
            [
              {
                "params": [
                  "value"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "mean"
              }
            ]
          ],
          "tags": []
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "Available measurements",
      "transform": "table",
      "type": "table"
    }
  ],
  "schemaVersion": 18,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "",
  "title": "Available measurements",
  "uid": "mKDpNERMz",
  "version": 2
}
```

**Comment by mpvader** [comment]
![image](https://user-images.githubusercontent.com/5200296/82207385-0886dc00-990a-11ea-8bd6-9be6072567f9.png)

**Comment by bbrantley** [comment]
After looking at it for a bit, I don't think increasing the measurements query cap will have any impact on the performance of influx the way we are using it.  I would try increasing it much higher, possibly to 1000 or more, and see if it works okay, just because we already have devices generating very close to 250 dbus paths.

**Comment by mpvader** [comment]
Understood - thanks Ben!

**Comment by mman** [comment]
@dirkjanfaber Could you please transfer this issue to https://github.com/victronenergy/venus-grafana repo? I'd like to investigate this a bit more in the future... Thanks!

**Comment by dirkjanfaber** [comment]
Continued here: https://github.com/victronenergy/venus-grafana/issues/6
