### ISSUE TITLE
Include a basic dashboard example into the venus-docker-grafana image

### ISSUE THREAD

**Issue by mark-cor** [victronenergy/venus-docker-grafana#9]
Particularly for users that are not familiar with Grafana functionality/setup or the Victron dbus path strategy, it would be beneficial to include a basic dashboard example into the venus-docker-grafana image as default.

This would enable users to have a functioning dashboard either immediately or with minimal additional configuration/adaption. It also allow the setup of existing panels/graphs to be used as an example for other new panels/graphs.

The dashboard shown below was created for this purpose:
![image](https://user-images.githubusercontent.com/65545165/83151840-6bfdde80-a140-11ea-94c3-809a0ab64259.png)

The related json file is in the zip file below - please add this dashboard into the venus-docker-grafana image.
[Example Dashboard-1590672479080.zip](https://github.com/victronenergy/venus-docker-grafana/files/4695966/Example.Dashboard-1590672479080.zip)

**Comment by mman** [comment]
Will be addressed in the new https://github.com/victronenergy/venus-grafana docker image. Feel free to reopen/followup there with ideas how to design the default dashboards. @dirkjanfaber Please close the issue.
